language: node_js
sudo: false
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
env:
  global:
  - secure: J+ahu8EtsOzhGFGWbe8oBPgRQCNTSy6uVk/zxi8c84+N5HBtLr3GC+YR5ZS2h0Ux2E53x7sWum10di8Ixr6EhuqSEjDmJGiZFW6oHTsXrMhT8X6RgHT+cPJnJwTLjlBZFA3JgT8Qyh1J3fcy3PiZjOMfyi+vt8Eihnw799QfuzE=
  - secure: KdN40eA1ExI0w09S9lMPfdqN98bXTBIr4jIr1kzZloQLuy6iLuBqvUKbOxvg6pu4hnxaKiSijve1cez1+KHCHC6rdTfVf62A4Q6pQUKwEAb42KtQZ4WHf7E0RA2i/5d+gUGqSNx+kR42o2blnYASZLrQkFem8cY5ENNbztLFEKE=
script: npm test
after_script: npm run-script inspect && npm install coveralls && cat ./coverage/lcov.info
  | coveralls
services:
- redis-server
